### ISSUE TITLE
App Crashes on receiving a push notification 

### ISSUE THREAD

**Issue by vgorla** [Countly/countly-sdk-cordova#17]
Hi Countly 

I am running the cordova countly SDK client. On receiving the message from the GCM the app is crashing with below error.

Can you please help? 

Class not found when unmarshalling: ly.count.android.sdk.messaging.Message
E/Parcel  (  848): java.lang.ClassNotFoundException: ly.count.android.sdk.messaging.Message
E/Parcel  (  848): 	at java.lang.Class.classForName(Native Method)
E/Parcel  (  848): 	at java.lang.Class.forName(Class.java:251)
E/Parcel  (  848): 	at java.lang.Class.forName(Class.java:216)
E/Parcel  (  848): 	at android.os.Parcel.readParcelableCreator(Parcel.java:2133)
E/Parcel  (  848): 	at android.os.Parcel.readParcelable(Parcel.java:2097)
E/Parcel  (  848): 	at android.os.Parcel.readValue(Parcel.java:2013)
E/Parcel  (  848): 	at android.os.Parcel.readArrayMapInternal(Parcel.java:2314)
E/Parcel  (  848): 	at android.os.Bundle.unparcel(Bundle.java:249)
E/Parcel  (  848): 	at android.os.Bundle.getString(Bundle.java:1118)
E/Parcel  (  848): 	at android.content.Intent.getStringExtra(Intent.java:4991)
E/Parcel  (  848): 	at com.android.server.am.ActivityStackSupervisor.startActivityLocked(ActivityStackSupervisor.java:1334)
E/Parcel  (  848): 	at com.android.server.am.ActivityStackSupervisor.startActivityMayWait(ActivityStackSupervisor.java:966)
E/Parcel  (  848): 	at com.android.server.am.ActivityManagerService.startActivityAsUser(ActivityManagerService.java:3890)
E/Parcel  (  848): 	at com.android.server.am.ActivityManagerService.startActivity(ActivityManagerService.java:3793)
E/Parcel  (  848): 	at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:159)
E/Parcel  (  848): 	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2532)
E/Parcel  (  848): 	at android.os.Binder.execTransact(Binder.java:404)
E/Parcel  (  848): 	at dalvik.system.NativeStart.run(Native Method)
E/Parcel  (  848): Caused by: java.lang.NoClassDefFoundError: ly/count/android/sdk/messaging/Message
E/Parcel  (  848): 	... 18 more
E/Parcel  (  848): Caused by: java.lang.ClassNotFoundException: Didn't find class "ly.count.android.sdk.messaging.Message" on path: DexPathList[[directory "."],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
E/Parcel  (  848): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:67)
E/Parcel  (  848): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
E/Parcel  (  848): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
E/Parcel  (  848): 	... 18 more
W/dalvikvm(30502): threadid=21: thread exiting with uncaught exception (group=0x41728da0)
E/AndroidRuntime(30502): FATAL EXCEPTION: IntentService[CountlyMessagingService]
E/AndroidRuntime(30502): Process: com.ionicframework.myapp119191, PID: 30502
E/AndroidRuntime(30502): android.content.ActivityNotFoundException: Unable to find explicit activity class {com.ionicframework.myapp119191/ly.count.android.sdk.messaging.ProxyActivity}; have you declared this activity in your AndroidManifest.xml?
E/AndroidRuntime(30502): 	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1648)
E/AndroidRuntime(30502): 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1442)
E/AndroidRuntime(30502): 	at android.app.ContextImpl.startActivity(ContextImpl.java:1371)
E/AndroidRuntime(30502): 	at android.app.ContextImpl.startActivity(ContextImpl.java:1353)

Thanks 
Vinod

**Comment by vgorla** [comment]
The solution to the above problem is add below to the platforms/android/AndroidManifest.xml within the <application> tags.

<activity android:label="@string/app_name" android:name="ly.count.android.sdk.messaging.ProxyActivity" android:noHistory="true" android:theme="@android:style/Theme.Translucent" />
